apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-workshop
  namespace:  {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: kubernetes-workshop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        pod: kubernetes-workshop
    spec:
      containers:
        - name: kubernetes-workshop
          image: reversearrow/kubernetes-workshop:latest
          env:
            - name: user
              valueFrom:
                secretKeyRef:
                  name: my-first-secret
                  key: "user"
            - name: password
              valueFrom:
                 secretKeyRef:
                   name: my-first-secret
                   key: "password"