apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-workshop-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/reversearrow/kubernetes-workshop.git
    path: deployment/helm-chart
    targetRevision: HEAD
    helm:
      releaseName: kubernetes-workshop
      valueFiles:
        - values-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prod