apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubernetes-workshop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: kubernetes workshop
  sourceRepos:
    - '*'
  destinations:
    - namespace: kubernetes-workshop
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
    - namespace: dev
      server: https://kubernetes.default.svc